source 'https://github.com/CocoaPods/Specs.git'
target 'Locate' do
pod 'GoogleMaps'
pod 'GooglePlaces'
#end


#target 'GoogleMapIntApp' do
    # Comment this line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for iosExample
    
    pod 'RealtimeMessaging-iOS-Swift3'
    
    #target 'GoogleMapIntAppTests' do
        inherit! :search_paths
        # Pods for testing
    #end
    
    #target 'GoogleMapIntAppUITests' do
        inherit! :search_paths
        # Pods for testing
    #end
    
end
